import type { VocabularyFormData } from '../types/vocabulary.types';

export const getEmptyVocabularyFormData = (): VocabularyFormData => ({
  name: '',
  phoneticUs: '',
  phoneticUsAudioFilename: '',
  phoneticUsAudioOriginalUrl: '',
  phoneticUsAudioUploadMethod: 'url',
  phoneticUsAudioFile: null,
  phoneticUk: '',
  phoneticUkAudioFilename: '',
  phoneticUkAudioOriginalUrl: '',
  phoneticUkAudioUploadMethod: 'url',
  phoneticUkAudioFile: null,
  partOfSpeech: '',
  synonyms: '',
  translation: '',
  meaningClue: '',
  meaning: '',
  easyMeaning: '',
  sentenceOne: '',
  sentenceTwo: '',
  difficultyLevel: 'easy',
  dictionaryUrl: '',
  additionalInfo: '',
  term: undefined,
  week: undefined,
  channel: 'All',
  tags: '',
  lang: 'EN',
  displayOrder: 999,
  isActive: true,
});
