import type { FreeTextQuestionFormData } from '../types/freeTextQuestion.types';

export const getEmptyFreeTextQuestionFormData = (): FreeTextQuestionFormData => ({
  question: '',
  answer: '',
  description: '',
  questionA: '',
  answerA: '',
  questionB: '',
  answerB: '',
  questionC: '',
  answerC: '',
  questionD: '',
  answerD: '',
  questionE: '',
  answerE: '',
  questionF: '',
  answerF: '',
  explanation: '',
  difficultyLevel: 'easy',
  gradeLevel: '',
  subject: '',
  topic: '',
  term: undefined,
  week: undefined,
  channel: 'All',
  tags: '',
  lang: 'EN',
  displayOrder: 0,
  isActive: true,
});
